services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      UV_PROJECT_ENVIRONMENT: /opt/venv
      UV_LINK_MODE: copy
      DATA_DIR: /data/jobs
    ports:
      - "10011:10011"
    env_file:
      - .env
    volumes:
      - ../data:/data
    restart: unless-stopped
